2018-03-29T14:39:39.300Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error executing chaincode: transaction returned with failure: [composerchannel-bfced3b9]Calling chaincode Invoke() returned error response [Error: The current identity, with the name 'admin' and the identifier '9b2441910343e7e430eeb914589e44f3220b918aa0515e6413a6d83ceb54ce32', must be activated (ACTIVATION_REQUIRED)]. Sending ERROR message back to peer
    at /home/vagrant/hyperledger/server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-29T14:39:39.302Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: error executing chaincode: transaction returned with failure: [composerchannel-bfced3b9]Calling chaincode Invoke() returned error response [Error: The current identity, with the name 'admin' and the identifier '9b2441910343e7e430eeb914589e44f3220b918aa0515e6413a6d83ceb54ce32', must be activated (ACTIVATION_REQUIRED)]. Sending ERROR message back to peer","stack":"Error: Error trying to query business network. Error: error executing chaincode: transaction returned with failure: [composerchannel-bfced3b9]Calling chaincode Invoke() returned error response [Error: The current identity, with the name 'admin' and the identifier '9b2441910343e7e430eeb914589e44f3220b918aa0515e6413a6d83ceb54ce32', must be activated (ACTIVATION_REQUIRED)]. Sending ERROR message back to peer\n    at channel.queryByChaincode.then.catch (/home/vagrant/hyperledger/server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:820:34)\n    at <anonymous>"}$
2018-03-29T14:39:39.302Z ERROR   HLFConnection           :ping()                   {"message":"Error trying to ping. Error: Error trying to query business network. Error: error executing chaincode: transaction returned with failure: [composerchannel-bfced3b9]Calling chaincode Invoke() returned error response [Error: The current identity, with the name 'admin' and the identifier '9b2441910343e7e430eeb914589e44f3220b918aa0515e6413a6d83ceb54ce32', must be activated (ACTIVATION_REQUIRED)]. Sending ERROR message back to peer","stack":"Error: Error trying to ping. Error: Error trying to query business network. Error: error executing chaincode: transaction returned with failure: [composerchannel-bfced3b9]Calling chaincode Invoke() returned error response [Error: The current identity, with the name 'admin' and the identifier '9b2441910343e7e430eeb914589e44f3220b918aa0515e6413a6d83ceb54ce32', must be activated (ACTIVATION_REQUIRED)]. Sending ERROR message back to peer\n    at _checkRuntimeVersions.then.catch (/home/vagrant/hyperledger/server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:699:34)\n    at <anonymous>"}$
2018-03-29T14:44:38.837Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error executing chaincode: transaction returned with failure: [composerchannel-53c2492a]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '3' in collection with ID 'Asset:org.gov.fundtracker.MMDA' as the object already exists]. Sending ERROR message back to peer
    at /home/vagrant/hyperledger/server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-29T14:44:38.838Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-53c2492a]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '3' in collection with ID 'Asset:org.gov.fundtracker.MMDA' as the object already exists]. Sending ERROR message back to peer\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-53c2492a]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '3' in collection with ID 'Asset:org.gov.fundtracker.MMDA' as the object already exists]. Sending ERROR message back to peer\n\n    at _initializeChannel.then.then.then.then.catch (/home/vagrant/hyperledger/server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:927:34)\n    at <anonymous>"}$
