2018-03-15T19:50:43.698Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error executing chaincode: transaction returned with failure: [composerchannel-408dc5a4]Calling chaincode Invoke() returned error response [Error: Object with ID 'singo@carge-network' in collection with ID 'Participant:org.gov.fundtracker.MMDA' does not exist]. Sending ERROR message back to peer
    at /home/vagrant/hyperledger/server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-15T19:50:43.700Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: error executing chaincode: transaction returned with failure: [composerchannel-408dc5a4]Calling chaincode Invoke() returned error response [Error: Object with ID 'singo@carge-network' in collection with ID 'Participant:org.gov.fundtracker.MMDA' does not exist]. Sending ERROR message back to peer","stack":"Error: Error trying to query business network. Error: error executing chaincode: transaction returned with failure: [composerchannel-408dc5a4]Calling chaincode Invoke() returned error response [Error: Object with ID 'singo@carge-network' in collection with ID 'Participant:org.gov.fundtracker.MMDA' does not exist]. Sending ERROR message back to peer\n    at channel.queryByChaincode.then.catch (/home/vagrant/hyperledger/server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:820:34)\n    at <anonymous>"}$
2018-03-15T19:52:54.794Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error executing chaincode: transaction returned with failure: [composerchannel-11685fec]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID 'bingo@carge-network' in collection with ID 'Participant:org.gov.fundtracker.MMDA' as the object already exists]. Sending ERROR message back to peer
    at /home/vagrant/hyperledger/server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-15T19:52:54.795Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-11685fec]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID 'bingo@carge-network' in collection with ID 'Participant:org.gov.fundtracker.MMDA' as the object already exists]. Sending ERROR message back to peer\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-11685fec]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID 'bingo@carge-network' in collection with ID 'Participant:org.gov.fundtracker.MMDA' as the object already exists]. Sending ERROR message back to peer\n\n    at _initializeChannel.then.then.then.then.catch (/home/vagrant/hyperledger/server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:927:34)\n    at <anonymous>"}$
2018-03-15T19:53:22.504Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error executing chaincode: transaction returned with failure: [composerchannel-ff5d209f]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID 'bingo@carge-network' in collection with ID 'Participant:org.gov.fundtracker.MMDA' as the object already exists]. Sending ERROR message back to peer
    at /home/vagrant/hyperledger/server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-15T19:53:22.505Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-ff5d209f]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID 'bingo@carge-network' in collection with ID 'Participant:org.gov.fundtracker.MMDA' as the object already exists]. Sending ERROR message back to peer\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-ff5d209f]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID 'bingo@carge-network' in collection with ID 'Participant:org.gov.fundtracker.MMDA' as the object already exists]. Sending ERROR message back to peer\n\n    at _initializeChannel.then.then.then.then.catch (/home/vagrant/hyperledger/server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:927:34)\n    at <anonymous>"}$
