2018-03-29T01:38:40.620Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error executing chaincode: transaction returned with failure: [composerchannel-62e4c93b]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '6' in collection with ID 'Participant:org.gov.fundtracker.FundTransferApprover' as the object already exists]. Sending ERROR message back to peer
    at /home/vagrant/hyperledger/server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-29T01:38:40.624Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-62e4c93b]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '6' in collection with ID 'Participant:org.gov.fundtracker.FundTransferApprover' as the object already exists]. Sending ERROR message back to peer\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-62e4c93b]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '6' in collection with ID 'Participant:org.gov.fundtracker.FundTransferApprover' as the object already exists]. Sending ERROR message back to peer\n\n    at _initializeChannel.then.then.then.then.catch (/home/vagrant/hyperledger/server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:927:34)\n    at <anonymous>"}$
2018-03-29T01:49:47.196Z ERROR   HLFConnection           :createIdentity()         Register request failed trying to create identity {"0":{"stack":["{Error}fabric-ca request register failed with errors [[{\"code\":0,\"message\":\"Registration of 'S.bingoone@decentralizedgov-network' failed: Identity 'S.bingoone@decentralizedgov-network' is already registered\"}]] Error: fabric-ca request register failed with errors [[{\"code\":0,\"message\":\"Registration of 'S.bingoone@decentralizedgov-network' failed: Identity 'S.bingoone@decentralizedgov-network' is already registered\"}]]","    at IncomingMessage.<anonymous> (/home/vagrant/hyperledger/server/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:739:22)","    at emitNone (events.js:111:20)","    at IncomingMessage.emit (events.js:208:7)","    at endReadableNT (_stream_readable.js:1055:12)","    at _combinedTickCallback (internal/process/next_tick.js:138:11)","    at process._tickCallback (internal/process/next_tick.js:180:9)"]}}$
