2018-04-14T05:28:16.688Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error executing chaincode: transaction returned with failure: [composerchannel-6c43bd83]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '2' in collection with ID 'Asset:org.gov.fundtracker.Project' as the object already exists]. Sending ERROR message back to peer
    at /home/vagrant/hyperledger/server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-14T05:28:16.692Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-6c43bd83]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '2' in collection with ID 'Asset:org.gov.fundtracker.Project' as the object already exists]. Sending ERROR message back to peer\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-6c43bd83]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '2' in collection with ID 'Asset:org.gov.fundtracker.Project' as the object already exists]. Sending ERROR message back to peer\n\n    at _initializeChannel.then.then.then.then.catch (/home/vagrant/hyperledger/server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:927:34)\n    at <anonymous>"}$
